import {
  mkdir,
  writeFile,
} from 'node:fs/promises'
import {
  resolve,
} from 'node:path'
import {
  runAuditForDegree,
} from '../../src/audit/auditRunner'
import {
  getCaseGroupsForDegree,
  type PlaygroundDegree,
} from '../../src/cases/playgroundCases'
import type {
  AuditProofRecipe,
} from '../../src/audit/proofRecipes'

const warehouseDegrees =
  [
    4,
    6,
    8,
    10,
    12,
  ] as const satisfies
    readonly PlaygroundDegree[]

type WarehouseDegree =
  typeof warehouseDegrees[number]

type GeneratedWarehouseRecipe = {
  id:
    string

  source:
    'audit'

  degree:
    WarehouseDegree

  forbiddenSet:
    readonly number[]

  steps:
    AuditProofRecipe[
      'steps'
    ]

  finalOutdegreesL:
    readonly number[]

  finalOutdegreesR:
    readonly number[]
}

function generatedRecipeId(
  degree:
    WarehouseDegree,

  caseId:
    string,
) {
  return (
    `audit-d${degree}-${caseId}`
  )
}

function asWarehouseRecipe({
  degree,
  caseId,
  recipe,
}: {
  degree:
    WarehouseDegree

  caseId:
    string

  recipe:
    AuditProofRecipe
}): GeneratedWarehouseRecipe {
  return {
    id:
      generatedRecipeId(
        degree,
        caseId,
      ),

    source:
      'audit',

    degree,

    /*
     * IMPORTANT:
     *
     * runAuditForDegree labels each RESULT
     * by the canonical reversal class, but
     * recipe.forbiddenSet records the actual
     * member F or d-F on which the search
     * found the proof.
     *
     * The Warehouse preserves that actual
     * orientation so every displayed proof
     * sequence is literally valid for the
     * F shown with it.
     */
    forbiddenSet: [
      ...recipe
        .forbiddenSet,
    ],

    steps:
      recipe.steps,

    finalOutdegreesL: [
      ...recipe
        .finalOutdegreesL,
    ],

    finalOutdegreesR: [
      ...recipe
        .finalOutdegreesR,
    ],
  }
}

function renderDegreeFile({
  degree,
  entries,
}: {
  degree:
    WarehouseDegree

  entries:
    Readonly<
      Record<
        string,
        GeneratedWarehouseRecipe
      >
    >
}) {
  const variableName =
    `d${degree}PreferredRecipes`

  return `import type {
  WarehouseProofRecipe,
} from '../../types'

/*
 * AUTO-GENERATED FILE.
 *
 * Source:
 *   src/audit/auditRunner.ts
 *
 * Regenerate with:
 *
 *   npm run warehouse:generate
 *
 * Do not edit this file by hand.
 * Human-preferred replacements belong in
 * data/preferredOverrides.ts.
 */
export const ${variableName}:
  Readonly<
    Record<
      string,
      WarehouseProofRecipe
    >
  > =
${JSON.stringify(
    entries,
    null,
    2,
  )}

export default
  ${variableName}
`
}

function renderGeneratedIndex() {
  const imports =
    warehouseDegrees
      .map(
        (degree) =>
          `import {
  d${degree}PreferredRecipes,
} from './d${degree}'`,
      )
      .join('\n')

  const entries =
    warehouseDegrees
      .map(
        (degree) =>
          `  ${degree}:
    d${degree}PreferredRecipes,`,
      )
      .join('\n\n')

  return `${imports}
import type {
  WarehouseDegree,
  WarehouseProofRecipe,
} from '../../types'

const generatedByDegree:
  Readonly<
    Record<
      WarehouseDegree,
      Readonly<
        Record<
          string,
          WarehouseProofRecipe
        >
      >
    >
  > = {
${entries}
}

export function getGeneratedPreferredRecipe({
  degree,
  caseId,
}: {
  degree:
    WarehouseDegree

  caseId:
    string
}) {
  return (
    generatedByDegree[
      degree
    ][
      caseId
    ] ??
    null
  )
}
`
}

async function generateDegree(
  degree:
    WarehouseDegree,
) {
  console.log(
    `Auditing d=${degree}...`,
  )

  const result =
    runAuditForDegree({
      degree,
    })

  if (
    result.unresolvedCases >
      0 ||
    result.searchLimitedCases >
      0 ||
    result.provedCases !==
      result.totalCases
  ) {
    throw new Error(
      [
        `Cannot generate d=${degree}.`,
        `${result.provedCases}/${result.totalCases} proved,`,
        `${result.unresolvedCases} exhausted,`,
        `${result.searchLimitedCases} search-limited.`,
      ].join(' '),
    )
  }

  const groups =
    getCaseGroupsForDegree(
      degree,
    )

  if (
    groups.length !==
      result.cases.length
  ) {
    throw new Error(
      `d=${degree}: audit returned ${result.cases.length} cases but the case generator has ${groups.length} reversal classes.`,
    )
  }

  const entries:
    Record<
      string,
      GeneratedWarehouseRecipe
    > = {}

  for (
    let index = 0;
    index <
      groups.length;
    index += 1
  ) {
    const group =
      groups[index]

    const auditCase =
      result.cases[index]

    if (
      group ===
        undefined ||
      auditCase ===
        undefined
    ) {
      throw new Error(
        `d=${degree}: missing case at index ${index}.`,
      )
    }

    if (
      auditCase.status !==
        'proved'
    ) {
      throw new Error(
        `d=${degree}: ${group.id} was not proved.`,
      )
    }

    entries[
      group.id
    ] =
      asWarehouseRecipe({
        degree,

        caseId:
          group.id,

        recipe:
          auditCase.recipe,
      })
  }

  console.log(
    `  ${result.provedCases}/${result.totalCases} certified in ${(result.elapsedMs / 1000).toFixed(2)} s`,
  )

  return entries
}

async function main() {
  const generatedDirectory =
    resolve(
      process.cwd(),
      'src/warehouse/data/generated',
    )

  await mkdir(
    generatedDirectory,
    {
      recursive:
        true,
    },
  )

  const generated:
    Partial<
      Record<
        WarehouseDegree,
        Record<
          string,
          GeneratedWarehouseRecipe
        >
      >
    > = {}

  /*
   * Audit every degree FIRST.
   *
   * We do not overwrite any Warehouse data
   * until all five audits have succeeded.
   * A failed run therefore cannot leave a
   * half-regenerated proof warehouse.
   */
  for (
    const degree
    of warehouseDegrees
  ) {
    generated[
      degree
    ] =
      await generateDegree(
        degree,
      )
  }

  console.log(
    'All audits succeeded. Writing Warehouse data...',
  )

  for (
    const degree
    of warehouseDegrees
  ) {
    const entries =
      generated[
        degree
      ]

    if (
      entries ===
        undefined
    ) {
      throw new Error(
        `Internal generator error: d=${degree} data is missing.`,
      )
    }

    await writeFile(
      resolve(
        generatedDirectory,
        `d${degree}.ts`,
      ),

      renderDegreeFile({
        degree,

        entries,
      }),

      'utf8',
    )
  }

  await writeFile(
    resolve(
      generatedDirectory,
      'index.ts',
    ),

    renderGeneratedIndex(),

    'utf8',
  )

  const total =
    warehouseDegrees.reduce(
      (
        sum,
        degree,
      ) =>
        sum +
        Object.keys(
          generated[
            degree
          ] ??
            {},
        ).length,

      0,
    )

  console.log(
    `Warehouse generation complete: ${total} reversal classes written.`,
  )
}

main().catch(
  (error) => {
    console.error(
      error,
    )

    process.exitCode =
      1
  },
)
